/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estimulos;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.Timer;

/**
 *
 * @author based-bulio
 */
public class MainUI extends javax.swing.JFrame {

    private EstimuloUbicacion au = new EstimuloUbicacion();
    private int n = 1, diff = 0;
    private boolean[] estimuloNuevo, estimuloViejo = null;
    private boolean isInicial = true;

    int delay = 2000; //milliseconds
    ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            borrarCuadros();
            btnIniciar.setEnabled(true);
            btnPresionar.setEnabled(true);
        }
    };
    Timer timer = new Timer(delay, taskPerformer);

    public MainUI() {
        initComponents();
        timer.setRepeats(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuadro1 = new javax.swing.JTextField();
        cuadro2 = new javax.swing.JTextField();
        cuadro3 = new javax.swing.JTextField();
        cuadro4 = new javax.swing.JTextField();
        cuadro5 = new javax.swing.JTextField();
        cuadro6 = new javax.swing.JTextField();
        cuadro7 = new javax.swing.JTextField();
        cuadro8 = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnPresionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        cuadro1.setEditable(false);
        cuadro1.setFocusable(false);

        cuadro2.setEditable(false);
        cuadro2.setFocusable(false);

        cuadro3.setEditable(false);
        cuadro3.setFocusable(false);

        cuadro4.setEditable(false);
        cuadro4.setFocusable(false);

        cuadro5.setEditable(false);
        cuadro5.setFocusable(false);

        cuadro6.setEditable(false);
        cuadro6.setFocusable(false);

        cuadro7.setEditable(false);
        cuadro7.setFocusable(false);

        cuadro8.setEditable(false);
        cuadro8.setFocusable(false);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnPresionar.setText("Presionar");
        btnPresionar.setEnabled(false);
        btnPresionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPresionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnPresionar))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        btnIniciar.setEnabled(false);
        estimuloNuevo = au.nuevoEstimulo();
        if (isInicial) {
            estimuloViejo = estimuloNuevo; //Estimulo base
            isInicial = false;
            timer.start();
            iluminarCualFue(estimuloNuevo, Color.YELLOW);
            diff++;
        } else {
            timer.start();
            iluminarCualFue(estimuloNuevo, Color.YELLOW);
            diff++;
        }


    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPresionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresionarActionPerformed
        btnPresionar.setEnabled(false);
        if (timer.isRunning()) {

            if (n == diff) {
                if (estimuloNuevo.equals(estimuloViejo)) {
                    iluminarCualFue(estimuloNuevo, Color.GREEN);
                } else {
                    iluminarCualFue(estimuloNuevo, Color.RED);
                }
            } else {
                iluminarCualFue(estimuloNuevo, Color.RED);
            }

            diff = 0;
            isInicial = true;

            estimuloViejo = null;
        }

    }//GEN-LAST:event_btnPresionarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
////        if(evt.getKeyCode()==KeyEvent.VK_G){
//            if(cual==2){
//                
//            }
//        }else if(evt.getKeyCode()==KeyEvent.VK_L){
//            
//        }
    }//GEN-LAST:event_formKeyPressed

    private int iluminarCualFue(boolean estimulo[], Color color) {
        int cual = -1;
        for (int i = 0; i < estimulo.length; i++) {
            if (estimulo[i]) {
                cual = i + 1;
                break;
            }
        }
        switch (cual) {
            case 1:
                cuadro1.setBackground(color);
                break;
            case 2:
                cuadro2.setBackground(color);
                break;
            case 3:
                cuadro3.setBackground(color);
                break;
            case 4:
                cuadro4.setBackground(color);
                break;
            case 5:
                cuadro5.setBackground(color);
                break;
            case 6:
                cuadro6.setBackground(color);
                break;
            case 7:
                cuadro7.setBackground(color);
                break;
            case 8:
                cuadro8.setBackground(color);
                break;
            default:
                btnIniciar.setText("algo paso lol");
                break;
        }

        return cual;
    }

    private void borrarCuadros() {
        cuadro1.setBackground(Color.WHITE);
        cuadro2.setBackground(Color.WHITE);
        cuadro3.setBackground(Color.WHITE);
        cuadro4.setBackground(Color.WHITE);
        cuadro5.setBackground(Color.WHITE);
        cuadro6.setBackground(Color.WHITE);
        cuadro7.setBackground(Color.WHITE);
        cuadro8.setBackground(Color.WHITE);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPresionar;
    private javax.swing.JTextField cuadro1;
    private javax.swing.JTextField cuadro2;
    private javax.swing.JTextField cuadro3;
    private javax.swing.JTextField cuadro4;
    private javax.swing.JTextField cuadro5;
    private javax.swing.JTextField cuadro6;
    private javax.swing.JTextField cuadro7;
    private javax.swing.JTextField cuadro8;
    // End of variables declaration//GEN-END:variables
}
